### ISSUE TITLE
Incorrect names of SkyView image sources in finding chart

### ISSUE THREAD

**Issue by emdailey** [naojsoft/spot#7]
In Finding Chart Image Source, "SkyView: AKAIR ..." should be "SkyView: AKARI ...".

**Comment by ejeschke** [comment]
Thanks, @emdailey! Can you confirm fixed by pulling changes and reinstalling? I was able to fetch from an AKARI catalog.

**Comment by emdailey** [comment]
Confirmed that it works now.

**Comment by emdailey** [comment]
In Finding Chart Image Source, "SkyView: NAVSS" should be "SkyView: NVSS". (NRAO VLA Sky Survey)

**Comment by ejeschke** [comment]
> In Finding Chart Image Source, "SkyView: NAVSS" should be "SkyView: NVSS". (NRAO VLA Sky Survey)

Thank you! Fixed in 366e302e3c854673de3ce73cb097b6486aaee268
